blank_issues_enabled: false
contact_links:
  - name: ğŸ“ƒ CI/CD Issue
    url: https://docs-ui-kit-btplc.ps.intdigital.ee.co.uk/docs/contributing/intro#cicd
    about: Continuous Integration and Continuous Delivery questions.
  - name: â¤´ï¸ Boilerplate
    url: https://docs-ui-kit-btplc.ps.intdigital.ee.co.uk/docs/contributing/intro#boilerplate
    about: Boilerplate's issues, additional features, migration, testing etc.
  - name: ğŸ¤” Questions and Help
    url: https://btconsumer.slack.com/archives/C012Y4GV34M
    about: Looking for help with FE Framework? Please refer to the `#FE-Framework` channel on Slack.
  - name: ğŸš€ Code Style Guideliens
    url: https://docs-ui-kit-btplc.ps.intdigital.ee.co.uk/docs/contributing/intro#code-style-guidelines
    about: Templates, initial setup, git workflows and more.
